import { B612 } from 'next/font/google'
import { ReactNode } from 'react'
import './globals.css'

const b612Mono = B612({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${b612Mono.className} h-screen w-full bg-carbon bg-mobile bg-cover bg-no-repeat md:h-full  md:bg-desktop`}
      >
        {children}
      </body>
    </html>
  )
}
